/* insert users */
INSERT INTO seapal.benutzer (benutzername, passwort, vorname, nachname, mail, geburtsdatum, registrierung) VALUES ("dominic", "pwd", "Dominic", "Eschbach", "doeschba@htwg-konstanz.de", DATE("2012-07-04"), DATE("2012-10-03"));
INSERT INTO seapal.benutzer (benutzername, passwort, vorname, nachname, mail, geburtsdatum, registrierung) VALUES ("timo", "pwd", "Timo", "Partl", "tipartl@htwg-konstanz.de", DATE("2012-07-02"), DATE("2012-10-03"));

/* insert boats */
INSERT INTO seapal.bootinfo (bootname, registernummer, segelzeichen, heimathafen, yachtclub, eigner, versicherung, rufzeichen, typ, konstrukteur, laenge, breite, tiefgang, masthoehe, verdraengung, rigart, baujahr, motor, tankgroesse, wassertankgroesse, abwassertankgroesse, grosssegelgroesse, genuagroesse, spigroesse) VALUES ("Titanic", 101, "TI101", "New York", "New York Yacht Club", "George Boat", "Württembergische", "TI", "Schiff", "Peter Schiff", 200, 50, 7, 10, 1000, "T34", 1993, "Duotec 100", 500, 50, 30, 10, 25, 13);
INSERT INTO seapal.bootinfo (bootname, registernummer, segelzeichen, heimathafen, yachtclub, eigner, versicherung, rufzeichen, typ, konstrukteur, laenge, breite, tiefgang, masthoehe, verdraengung, rigart, baujahr, motor, tankgroesse, wassertankgroesse, abwassertankgroesse, grosssegelgroesse, genuagroesse, spigroesse) VALUES ("Queen Mary 2", 80, "QM80", "Dover", "Dover Yacht Club", "Hans Ebert", "Wüstenrot", "QM", "Schiff", "Rainer Berger", 200, 50, 7, 10, 1000, "T20", 1993, "Duotec 100", 500, 50, 30, 10, 25, 13);
INSERT INTO seapal.bootinfo (bootname, registernummer, segelzeichen, heimathafen, yachtclub, eigner, versicherung, rufzeichen, typ, konstrukteur, laenge, breite, tiefgang, masthoehe, verdraengung, rigart, baujahr, motor, tankgroesse, wassertankgroesse, abwassertankgroesse, grosssegelgroesse, genuagroesse, spigroesse) VALUES ("MS Deutschland", 150, "MSD15", "Hamburg", "Hamburg Yacht Club", "Peter Miller", "Allianz", "MSD", "Schiff", "Emil Klaus", 200, 50, 7, 10, 1000, "T27", 1993, "Duotec 100", 500, 50, 30, 10, 25, 13);

/* insert trips */
INSERT INTO seapal.tripinfo (bnr, titel, von, nach, skipper, crew, tstart, tende, tdauer, motor, tank) VALUES (1, "Bodenseetrip", "Konstanz", "Meersburg", "Hr. Hein", "Martin Felix Manuel", DATE("2012-07-02"), DATE("2012-07-02"), 300, 1241, true);
INSERT INTO seapal.tripinfo (bnr, titel, von, nach, skipper, crew, tstart, tende, tdauer, motor, tank) VALUES (2, "Trip nach Friedrichshafen", "Konstanz", "Friedrichshafen", "Hr. Maier", "Martin Felix Manuel", DATE("2012-02-03"), DATE("2012-02-03"), 300, 1241, true);

INSERT INTO seapal.wegpunkte (tnr, name, btm, dtm, lat, lng, sog, cog, manoever, vorsegel, wdate, wtime, marker, windStrength, windDirection, airPressure, temperature, clouds, rain, waveHeight, waveDirection) VALUES (1, "Marker 1", "010°", "05 kn", "47°39.39N", "009°11.20E", "07 kn", "005°", "Tack", "Genua1", "2012-07-02", "14:00", "Marker 2", "2 - leichte Brise", "W", "760 mmHg", "+15°C", "Haufenwolken", "kein Regen", "015 cm", "W");
INSERT INTO seapal.wegpunkte (tnr, name, btm, dtm, lat, lng, sog, cog, manoever, vorsegel, wdate, wtime, marker, windStrength, windDirection, airPressure, temperature, clouds, rain, waveHeight, waveDirection) VALUES (1, "Marker 2", "005°", "05 kn", "47°39.39N", "009°11.25E", "05 kn", "005°", "Tack", "Genua1", "2012-07-02", "14:05", "Marker 3", "2 - leichte Brise", "W", "760 mmHg", "+15°C", "Haufenwolken", "kein Regen", "020 cm", "W");
INSERT INTO seapal.wegpunkte (tnr, name, btm, dtm, lat, lng, sog, cog, manoever, vorsegel, wdate, wtime, marker, windStrength, windDirection, airPressure, temperature, clouds, rain, waveHeight, waveDirection) VALUES (1, "Marker 3", "007°", "08 kn", "47°39.39N", "009°11.55E", "05 kn", "005°", "Jibe", "Genua1", "2012-07-02", "14:10", "Marker 4", "2 - leichte Brise", "W", "760 mmHg", "+15°C", "Haufenwolken", "kein Regen", "015 cm", "W");
INSERT INTO seapal.wegpunkte (tnr, name, btm, dtm, lat, lng, sog, cog, manoever, vorsegel, wdate, wtime, marker, windStrength, windDirection, airPressure, temperature, clouds, rain, waveHeight, waveDirection) VALUES (1, "Marker 4", "010°", "05 kn", "47°39.44N", "009°11.70E", "02 kn", "005°", "Jibe", "Genua1", "2012-07-02", "14:15", "Marker 5", "2 - leichte Brise", "W", "760 mmHg", "+15°C", "Haufenwolken", "kein Regen", "010 cm", "W");
INSERT INTO seapal.wegpunkte (tnr, name, btm, dtm, lat, lng, sog, cog, manoever, vorsegel, wdate, wtime, marker, windStrength, windDirection, airPressure, temperature, clouds, rain, waveHeight, waveDirection) VALUES (2, "Marker 1", "010°", "05 kn", "47°39.39N", "009°11.20E", "07 kn", "005°", "Tack", "Genua1", "2012-02-03", "14:00", "Marker 2", "2 - leichte Brise", "S", "760 mmHg", "+18°C", "Schichtwolken", "kein Regen", "015 cm", "S");
INSERT INTO seapal.wegpunkte (tnr, name, btm, dtm, lat, lng, sog, cog, manoever, vorsegel, wdate, wtime, marker, windStrength, windDirection, airPressure, temperature, clouds, rain, waveHeight, waveDirection) VALUES (2, "Marker 2", "010°", "02 kn", "47°39.44N", "009°11.80E", "03 kn", "005°", "Jibe", "Genua1", "2012-02-03", "14:15", "Marker 3", "2 - leichte Brise", "S", "760 mmHg", "+18°C", "Schichtwolken", "kein Regen", "020 cm", "S");
INSERT INTO seapal.wegpunkte (tnr, name, btm, dtm, lat, lng, sog, cog, manoever, vorsegel, wdate, wtime, marker, windStrength, windDirection, airPressure, temperature, clouds, rain, waveHeight, waveDirection) VALUES (2, "Marker 3", "025°", "05 kn", "47°39.46N", "009°12.59E", "04 kn", "005°", "Tack", "Genua1", "2012-02-03", "14:35", "Marker 4", "2 - leichte Brise", "S", "760 mmHg", "+18°C", "Schichtwolken", "kein Regen", "015 cm", "S");
INSERT INTO seapal.wegpunkte (tnr, name, btm, dtm, lat, lng, sog, cog, manoever, vorsegel, wdate, wtime, marker, windStrength, windDirection, airPressure, temperature, clouds, rain, waveHeight, waveDirection) VALUES (2, "Marker 4", "015°", "01 kn", "47°39.49N", "009°13.20E", "07 kn", "005°", "Jibe", "Genua1", "2012-02-03", "14:59", "Marker 5", "2 - leichte Brise", "S", "760 mmHg", "+18°C", "Schichtwolken", "kein Regen", "010 cm", "S");
